spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres